name: Test cron
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # Put here!!

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Every time
        run: echo "This step will always run"
